# Generated by Django 5.1.6 on 2025-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('degree', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
